# Plimpton 322 (1)

* [A Remarkable Collection of Babylonian Mathematical Texts: Manuscripts in the Schøyen Collection: Cuneiform Texts I (Sources and Studies in the History of Mathematics and Physical Sciences): Friberg, Jöran: 9780387345437: Books - Amazon](https://www.amazon.com/Remarkable-Collection-Babylonian-Mathematical-Texts-dp-0387345434/dp/0387345434/ref=mt_other?_encoding=UTF8&me=&qid=)

In [20]:
df1.drop(df1.index[[10,14]]).iloc[:,1].values.astype(int)

array([  119,  3367,  4601, 12709,    65,   319,  2291,   799,   481,
        4961,  1679,   161,  1771])

In [21]:
df1.drop(df1.index[[10,14]]).iloc[:,2].values.astype(int)

array([  169,  4825,  6649, 18541,    97,   481,  3541,  1249,   769,
        8161,  2929,   289,  3229])

In [24]:
import numpy as np

In [29]:
np.array(list(zip(df1.drop(df1.index[[10,14]]).iloc[:,1].values.astype(int),
                  df1.drop(df1.index[[10,14]]).iloc[:,2].values.astype(int))))

array([[  119,   169],
       [ 3367,  4825],
       [ 4601,  6649],
       [12709, 18541],
       [   65,    97],
       [  319,   481],
       [ 2291,  3541],
       [  799,  1249],
       [  481,   769],
       [ 4961,  8161],
       [ 1679,  2929],
       [  161,   289],
       [ 1771,  3229]])

In [33]:
df0.iloc[:,1]

0                  1 59
1                 56 07
2               1 16 41
3               3 31 49
4                  1 05
5                  5 19
6                 38 11
7                 13 19
8           9 01 [8] 01
9               1 22 41
10                   45
11                27 59
12       7 12 01 [2 41]
13                29 31
14    56 56 [28] (alt.)
Name: ÍB.SI8 of the width, dtype: object

In [34]:
tuple(map(int,df.iloc[:,1][0].split()))

(1, 59)

In [35]:
tuple(map(int,df.iloc[:,2][0].split()))

(2, 49)

In [43]:
df0.take([0])

takiltum of the diagonal from which 1 is tornout so that thewidth comes up  \
0                                       (1) 59 00 15                           

  ÍB.SI8 of the width ÍB.SI8 of the diagonal its line  
0                1 59                   2 49      1st

* [【Python】記数法の変換（10進数⇔n進数） - 理系のための備忘録](https://science-log.com/python%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0tips%E9%9B%86/%E3%80%90python%E3%80%91%E8%A8%98%E6%95%B0%E6%B3%95%E3%81%AE%E5%A4%89%E6%8F%9B/)

In [37]:
def Dec_to_N(num, base):
    if num >= base:
        yield from Dec_to_N(num // base, base)
    yield num % base

In [38]:
def N_to_Dec(digits, base):
    num = 0
    for digit in digits:
        num = num * base + digit
    return num

In [50]:
N_to_Dec(map(int,df.iloc[:,1][0].split()), 60)

119

In [51]:
N_to_Dec(map(int,df.iloc[:,2][0].split()), 60)

169

In [44]:
df1.take([0])

or Short Side Diagonal  Row #
0  (1).9834028        119      169      1

## 11行目に着目

In [45]:
df0.take([10])

takiltum of the diagonal from which 1 is tornout so that thewidth comes up  \
10                                          (1) 33 45                           

   ÍB.SI8 of the width ÍB.SI8 of the diagonal its line  
10                  45                   1 15     11th

In [48]:
N_to_Dec(map(int,df.iloc[:,1][10].split()), 60)

45

In [49]:
N_to_Dec(map(int,df.iloc[:,2][10].split()), 60)

75

In [119]:
pd.read_html(res)[1].take([10])

or Short Side Diagonal  Row #
10  (1).5625        45*      75*     11

In [53]:
N_to_Dec(list(map(int,df0.iloc[:,1][10].split())), 60)/15

3.0

In [52]:
N_to_Dec(list(map(int,df0.iloc[:,2][10].split())), 60)/15

5.0

In [54]:
60/15

4.0

In [57]:
import math

In [58]:
math.sqrt(75**2 - 45**2)

60.0

In [59]:
45**2 / 60**2

0.5625

In [60]:
75**2 / 60**2

1.5625

In [61]:
(3**2 / 4**2, 5**2 / 4**2)

(0.5625, 1.5625)

In [62]:
def _modf(x):
    f, _ = math.modf(x)
    return int(f*(10**str(f)[::-1].find('.')))

In [63]:
_modf(1.5625)

5625

In [64]:
tuple(Dec_to_N(_modf(1.5625),60))

(1, 33, 45)

In [65]:
df0.take([10])

takiltum of the diagonal from which 1 is tornout so that thewidth comes up  \
10                                          (1) 33 45                           

   ÍB.SI8 of the width ÍB.SI8 of the diagonal its line  
10                  45                   1 15     11th

## Plimpton 322の用途

問: 次の等式を満たす $x$ を求めよ:
$$x - \frac{1}{x} = 1.5$$

解: $x = 2$

$x - \frac{1}{x} = c$ としたとき、$v_{1} = \frac{c}{2}$、$v_{3} = 1 + {v_{1}}^2 = 1 + (\frac{c}{2})^2$、$v_{4} = \sqrt{v_{3}} = \sqrt{1 + (\frac{c}{2})^2}$ と置くと、次の公式が成り立つ:
\begin{eqnarray}
x &=& v_{4} + v_{1} \\
\frac{1}{x} &=& v_{4} - v_{1}
\end{eqnarray}

$v_{3} = 1 + (\frac{1.5}{2})^2 = 1.5625$、$v_{4} = \sqrt{v_{3}} = 1.25$、$v_{1} = \frac{1.5}{2} = 0.75$ なので、$x = v_{4} + v_{1} = 2$ が成り立つ。なお、このとき $\frac{1}{x} = v_{4} - v_{1} = 0.5$ も成り立っている。

なお、$v_{3}$ はPlimpton 322の1カラム目、$v_{1}$ は2カラム目、$v_{4}$ は3カラム目に対応する。

$v_{1} = \frac{1}{2}(x-\frac{1}{x})$, $1$, $v_{4} = \frac{1}{2}(x+\frac{1}{x})$ はピタゴラスの三数である。

In [67]:
# v1
1.5/2

0.75

In [205]:
# v3
1+(1.5/2)**2

1.5625

In [66]:
# v4
math.sqrt(1.5625)

1.25

In [68]:
df0.take([10])

takiltum of the diagonal from which 1 is tornout so that thewidth comes up  \
10                                          (1) 33 45                           

   ÍB.SI8 of the width ÍB.SI8 of the diagonal its line  
10                  45                   1 15     11th

In [64]:
tuple(Dec_to_N(_modf(1.5625),60))

(1, 33, 45)

In [73]:
N_to_Dec(list(map(int,df0.iloc[:,1][10].split())), 60) 

45

In [74]:
N_to_Dec(list(map(int,df0.iloc[:,2][10].split())), 60) 

75

In [75]:
math.sqrt(75**2 - 45**2)

60.0

In [78]:
# v1, 1, v4
(45/60, 60/60, 75/60)

(0.75, 1.0, 1.25)

In [79]:
math.sqrt(0.75**2 + 1**2)

1.25

In [80]:
df1

or Short Side Diagonal  Row #
0   (1).9834028        119      169      1
1   (1).9491586       3367     4825      2
2   (1).9188021       4601     6649      3
3   (1).8862479      12709    18541      4
4   (1).8150077         65       97      5
5   (1).7851929        319      481      6
6   (1).7199837       2291     3541      7
7   (1).6927094        799     1249      8
8   (1).6426694        481      769      9
9   (1).5861226       4961     8161     10
10     (1).5625        45*      75*     11
11  (1).4894168       1679     2929     12
12  (1).4500174        161      289     13
13  (1).4302388       1771     3229     14
14  (1).3871605        56*     106*     15

$v_{3} = 1 + {v_{1}}^2 = 1 + (\frac{c}{2})^2$

In [81]:
(1.5/2)**2

0.5625

タブレットでは肝心の $x$ の値のカラムが欠けているのではないか!?

課題 1: Plimton 322の数の表の各列に対応する $x$ の値を求めよ。

課題2: Plimpton 322の数表の左端にカラムを追加し、$x$ の値を計算して埋めよ。