In [10]:
from datascience import *
import numpy as np

In [9]:
x = make_array([1,2,3])

In [12]:
x

array([[1, 2, 3]])

In [13]:
x.dtype

dtype('int64')

In [14]:
type(x)

numpy.ndarray

In [15]:
y=[1,2,3]

In [16]:
type(y)

list

In [18]:
z=np.array([[1,2,3])

In [19]:
type(z)

numpy.ndarray

In [29]:
Table().from_array(make_array([1,2,3]))

TypeError: 'NoneType' object is not iterable

In [27]:
x

array([[1, 2, 3]])

In [31]:
z=Table().with_columns('Number of petals', make_array(8, 34, 5))

In [32]:
type(z)

datascience.tables.Table

In [33]:
z.hist()

In [42]:
x.with_rows([[[1,2,3],2,3],[4,5,6]])

/Users/manabu/.pyenv/versions/anaconda3-2021.11/envs/jb/lib/python3.9/site-packages/datascience/tables.py:920: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  values = np.array(tuple(values))


a         | b    | c
[1, 2, 3] | 2    | 3
4         | 5    | 6

In [43]:
x=Table(['a','b','c'])

In [45]:
x.with_row([[1,2,3],[4,5,6],[7,8,9]])

a       | b       | c
[1 2 3] | [4 5 6] | [7 8 9]